[CmdletBinding()]
param(
    [string]$WorldConfig = 'D:\AzerothCore\runtime\configs\worldserver.conf',
    [string]$OutputPath = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
if (-not $OutputPath) {
    $OutputPath = Join-Path $repoRoot 'modules\custom\mod-mythic-rewards\data\sql\db-world\mod_mythic_rewards.sql'
}

$config = Get-Item -LiteralPath $WorldConfig -ErrorAction SilentlyContinue
if (-not $config) {
    $config = Get-ChildItem 'D:\AzerothCore\runtime' -Filter worldserver.conf -File -Recurse | Select-Object -First 1
}
if (-not $config) { throw '找不到 worldserver.conf，无法读取世界数据库结构。' }
$line = Get-Content -LiteralPath $config.FullName | Where-Object { $_ -match '^WorldDatabaseInfo\s*=' } | Select-Object -First 1
if (-not $line) { throw 'worldserver.conf 缺少 WorldDatabaseInfo。' }
$dsn = (($line -split '=', 2)[1]).Trim().Trim('"').Split(';')
if ($dsn.Count -lt 5) { throw 'WorldDatabaseInfo 格式无效。' }
$mysql = Get-ChildItem 'D:\AzerothCore\mysql' -Filter mysql.exe -File -Recurse | Select-Object -First 1
if (-not $mysql) { throw '找不到便携 MySQL 客户端。' }

$env:MYSQL_PWD = $dsn[3]
try {
    $columns = @(& $mysql.FullName --protocol=tcp -h $dsn[0] -P $dsn[1] -u $dsn[2] -N -B `
        -e 'SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=''item_template'' ORDER BY ORDINAL_POSITION' $dsn[4])
    if ($LASTEXITCODE -ne 0 -or $columns.Count -lt 100) { throw '读取 item_template 列失败。' }
}
finally {
    Remove-Item Env:MYSQL_PWD -ErrorAction SilentlyContinue
}

function Get-CloneExpression([string]$column) {
    $quoted = 'src.`' + $column + '`'
    $scale = 'POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED))'
    switch -Regex ($column) {
        '^entry$' { return '9000000 + (v.variant_id * 100000) + src.entry' }
        '^name$' { return "CONCAT(src.name, ' [Mythic ', v.item_level, ']')" }
        '^Quality$' { return '4' }
        '^ItemLevel$' { return 'v.item_level' }
        '^RequiredLevel$' { return '80' }
        '^RequiredReputation(Faction|Rank)$' { return '0' }
        '^maxcount$' { return '0' }
        '^ScalingStat(Distribution|Value)$' { return '0' }
        '^stat_value\d+$' { return "ROUND($quoted * $scale * IF(src.Quality = 3, 1.12, 1))" }
        '^dmg_(min|max)\d+$' { return "ROUND($quoted * $scale * IF(src.Quality = 3, 1.12, 1), 2)" }
        '^(armor|block|holy_res|fire_res|nature_res|frost_res|shadow_res|arcane_res)$' { return "ROUND(COALESCE($quoted, 0) * $scale * IF(src.Quality = 3, 1.12, 1))" }
        '^(BuyPrice|SellPrice)$' { return "ROUND($quoted * $scale)" }
        '^spellid_\d+$' { return '0' }
        '^spelltrigger_\d+$' { return '0' }
        '^spellcharges_\d+$' { return '0' }
        '^spellppmRate_\d+$' { return '0' }
        '^spellcooldown_\d+$' { return '-1' }
        '^spellcategory_\d+$' { return '0' }
        '^spellcategorycooldown_\d+$' { return '-1' }
        '^bonding$' { return '1' }
        '^startquest$' { return '0' }
        '^Random(Property|Suffix)$' { return '0' }
        '^itemset$' { return '0' }
        '^(area|Map|duration|ItemLimitCategory|HolidayId|DisenchantID)$' { return '0' }
        '^RequiredDisenchantSkill$' { return '-1' }
        '^ScriptName$' { return "''" }
        '^VerifiedBuild$' { return 'NULL' }
        default { return $quoted }
    }
}

$columnList = ($columns | ForEach-Object { '  `' + $_ + '`' }) -join ",`n"
$expressionList = ($columns | ForEach-Object { '  ' + (Get-CloneExpression $_) }) -join ",`n"
$sql = @"
-- Generated by scripts/generate-mythic-items.ps1 for the locked AzerothCore schema.
-- Custom item entries occupy 9,100,000 through 9,899,999.

CREATE TABLE IF NOT EXISTS ``mod_mythic_rewards_variant`` (
  ``variant_id`` tinyint unsigned NOT NULL,
  ``item_level`` smallint unsigned NOT NULL,
  PRIMARY KEY (``variant_id``),
  UNIQUE KEY ``uk_item_level`` (``item_level``)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM ``mod_mythic_rewards_variant``;
INSERT INTO ``mod_mythic_rewards_variant`` (``variant_id``, ``item_level``) VALUES
(1,200),(2,207),(3,213),(4,219),(5,226),(6,232),(7,239),(8,245);

CREATE TABLE IF NOT EXISTS ``mod_mythic_rewards_level_v2`` (
  ``min_mythic_level`` tinyint unsigned NOT NULL,
  ``max_mythic_level`` tinyint unsigned NOT NULL,
  ``end_variant_id`` tinyint unsigned NOT NULL,
  ``weekly_variant_id`` tinyint unsigned NOT NULL,
  ``money`` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (``min_mythic_level``, ``max_mythic_level``)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM ``mod_mythic_rewards_level_v2``;
INSERT INTO ``mod_mythic_rewards_level_v2``
(``min_mythic_level``, ``max_mythic_level``, ``end_variant_id``, ``weekly_variant_id``, ``money``) VALUES
(1,1,1,2,200000),(2,2,2,3,300000),(3,3,3,4,400000),(4,4,4,5,500000),
(5,5,5,6,600000),(6,6,6,7,700000),(7,255,7,8,800000);

CREATE TABLE IF NOT EXISTS ``mod_mythic_rewards_source`` (
  ``map_id`` smallint unsigned NOT NULL,
  ``source_entry`` int unsigned NOT NULL,
  PRIMARY KEY (``map_id``, ``source_entry``)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM ``mod_mythic_rewards_source``;
INSERT IGNORE INTO ``mod_mythic_rewards_source`` (``map_id``, ``source_entry``)
SELECT loot.map_id, loot.item_entry FROM (
  SELECT loot_ids.map_id, l.Item AS item_entry
  FROM (
    SELECT DISTINCT c.map AS map_id, ct.lootid
    FROM creature c JOIN creature_template ct ON ct.entry = c.id
    WHERE c.map IN (574,575,576,578,599,600,601,602,604,619,632,658) AND ct.lootid > 0
    UNION
    SELECT DISTINCT c.map AS map_id, heroic.lootid
    FROM creature c JOIN creature_template ct ON ct.entry = c.id
    JOIN creature_template heroic ON heroic.entry = ct.difficulty_entry_1
    WHERE c.map IN (574,575,576,578,599,600,601,602,604,619,632,658) AND heroic.lootid > 0
  ) loot_ids JOIN creature_loot_template l ON l.Entry = loot_ids.lootid
  WHERE l.Item > 0
  UNION
  SELECT loot_ids.map_id, r.Item AS item_entry
  FROM (
    SELECT DISTINCT c.map AS map_id, ct.lootid
    FROM creature c JOIN creature_template ct ON ct.entry = c.id
    WHERE c.map IN (574,575,576,578,599,600,601,602,604,619,632,658) AND ct.lootid > 0
    UNION
    SELECT DISTINCT c.map AS map_id, heroic.lootid
    FROM creature c JOIN creature_template ct ON ct.entry = c.id
    JOIN creature_template heroic ON heroic.entry = ct.difficulty_entry_1
    WHERE c.map IN (574,575,576,578,599,600,601,602,604,619,632,658) AND heroic.lootid > 0
  ) loot_ids JOIN creature_loot_template l ON l.Entry = loot_ids.lootid
  JOIN reference_loot_template r ON r.Entry = l.Reference
  WHERE l.Reference > 0 AND r.Item > 0
) loot JOIN item_template src ON src.entry = loot.item_entry
WHERE src.Quality BETWEEN 3 AND 4 AND src.ItemLevel BETWEEN 175 AND 232
  AND src.RequiredLevel <= 80 AND src.InventoryType NOT IN (0,12)
  AND src.class IN (2,4) AND src.itemset = 0 AND src.startquest = 0;

DELETE FROM ``item_template_locale`` WHERE ``ID`` BETWEEN 9100000 AND 9899999;
DELETE FROM ``item_template`` WHERE ``entry`` BETWEEN 9100000 AND 9899999;

INSERT INTO ``item_template`` (
$columnList
)
SELECT
$expressionList
FROM ``item_template`` src
JOIN (SELECT DISTINCT ``source_entry`` FROM ``mod_mythic_rewards_source``) source
  ON source.source_entry = src.entry
CROSS JOIN ``mod_mythic_rewards_variant`` v;

INSERT INTO ``item_template_locale`` (``ID``, ``locale``, ``Name``, ``Description``, ``VerifiedBuild``)
SELECT 9000000 + (v.variant_id * 100000) + locale.ID, locale.locale,
  CONCAT(locale.Name, IF(locale.locale IN ('zhCN','zhTW'), ' [大秘境 ', ' [Mythic '), v.item_level, ']'),
  locale.Description, NULL
FROM ``item_template_locale`` locale
JOIN (SELECT DISTINCT ``source_entry`` FROM ``mod_mythic_rewards_source``) source
  ON source.source_entry = locale.ID
CROSS JOIN ``mod_mythic_rewards_variant`` v;

CREATE TABLE IF NOT EXISTS ``mod_mythic_rewards_item_pool`` (
  ``map_id`` smallint unsigned NOT NULL,
  ``variant_id`` tinyint unsigned NOT NULL,
  ``source_entry`` int unsigned NOT NULL,
  ``item_entry`` int unsigned NOT NULL,
  PRIMARY KEY (``map_id``, ``variant_id``, ``source_entry``),
  KEY ``idx_pool`` (``map_id``, ``variant_id``)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM ``mod_mythic_rewards_item_pool``;
INSERT INTO ``mod_mythic_rewards_item_pool`` (``map_id``, ``variant_id``, ``source_entry``, ``item_entry``)
SELECT source.map_id, v.variant_id, source.source_entry,
  9000000 + (v.variant_id * 100000) + source.source_entry
FROM ``mod_mythic_rewards_source`` source CROSS JOIN ``mod_mythic_rewards_variant`` v;

DELETE FROM ``acore_string`` WHERE ``entry`` BETWEEN 85000 AND 85005;
INSERT INTO ``acore_string``
(``entry``, ``content_default``, ``locale_koKR``, ``locale_frFR``, ``locale_deDE``, ``locale_zhCN``, ``locale_zhTW``, ``locale_esES``, ``locale_esMX``, ``locale_ruRU``) VALUES
(85000, 'Mythic +{} reward: {}', '', '', '', '大秘境 +{} 奖励：{}', '', '', '', ''),
(85001, 'Mythic +{} reward mailed because your bags were full: {}', '', '', '', '背包已满，大秘境 +{} 奖励已邮寄：{}', '', '', '', ''),
(85002, 'Mythic +{} completed. No personal item this run; weekly reward progress was updated.', '', '', '', '大秘境 +{} 已完成。本次没有个人装备；每周奖励进度已更新。', '', '', '', ''),
(85003, 'Mythic +{} completed in time. Three personal items were awarded to the party.', '', '', '', '大秘境 +{} 限时完成，队伍共获得 3 件个人装备。', '', '', '', ''),
(85004, 'Mythic +{} completed over time. Two personal items were awarded to the party.', '', '', '', '大秘境 +{} 超时完成，队伍共获得 2 件个人装备。', '', '', '', ''),
(85005, 'Weekly Mythic reward for +{}: {}', '', '', '', '每周大秘境 +{} 奖励：{}', '', '', '', '');
"@

[IO.File]::WriteAllText([IO.Path]::GetFullPath($OutputPath), $sql + "`n", [Text.UTF8Encoding]::new($false))
Write-Host "已生成 $OutputPath（$($columns.Count) 个 item_template 列）。"
