-- Generated by scripts/generate-mythic-items.ps1 for the locked AzerothCore schema.
-- Custom item entries occupy 9,100,000 through 9,899,999.

CREATE TABLE IF NOT EXISTS `mod_mythic_rewards_variant` (
  `variant_id` tinyint unsigned NOT NULL,
  `item_level` smallint unsigned NOT NULL,
  PRIMARY KEY (`variant_id`),
  UNIQUE KEY `uk_item_level` (`item_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `mod_mythic_rewards_variant`;
INSERT INTO `mod_mythic_rewards_variant` (`variant_id`, `item_level`) VALUES
(1,200),(2,207),(3,213),(4,219),(5,226),(6,232),(7,239),(8,245);

CREATE TABLE IF NOT EXISTS `mod_mythic_rewards_level_v2` (
  `min_mythic_level` tinyint unsigned NOT NULL,
  `max_mythic_level` tinyint unsigned NOT NULL,
  `end_variant_id` tinyint unsigned NOT NULL,
  `weekly_variant_id` tinyint unsigned NOT NULL,
  `money` int unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`min_mythic_level`, `max_mythic_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `mod_mythic_rewards_level_v2`;
INSERT INTO `mod_mythic_rewards_level_v2`
(`min_mythic_level`, `max_mythic_level`, `end_variant_id`, `weekly_variant_id`, `money`) VALUES
(1,1,1,2,200000),(2,2,2,3,300000),(3,3,3,4,400000),(4,4,4,5,500000),
(5,5,5,6,600000),(6,6,6,7,700000),(7,255,7,8,800000);

CREATE TABLE IF NOT EXISTS `mod_mythic_rewards_source` (
  `map_id` smallint unsigned NOT NULL,
  `source_entry` int unsigned NOT NULL,
  PRIMARY KEY (`map_id`, `source_entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `mod_mythic_rewards_source`;
INSERT IGNORE INTO `mod_mythic_rewards_source` (`map_id`, `source_entry`)
SELECT loot.map_id, loot.item_entry FROM (
  SELECT loot_ids.map_id, l.Item AS item_entry
  FROM (
    SELECT DISTINCT c.map AS map_id, ct.lootid
    FROM creature c JOIN creature_template ct ON ct.entry = c.id
    WHERE c.map IN (574,575,576,578,599,600,601,602,604,619,632,658) AND ct.lootid > 0
    UNION
    SELECT DISTINCT c.map AS map_id, heroic.lootid
    FROM creature c JOIN creature_template ct ON ct.entry = c.id
    JOIN creature_template heroic ON heroic.entry = ct.difficulty_entry_1
    WHERE c.map IN (574,575,576,578,599,600,601,602,604,619,632,658) AND heroic.lootid > 0
  ) loot_ids JOIN creature_loot_template l ON l.Entry = loot_ids.lootid
  WHERE l.Item > 0
  UNION
  SELECT loot_ids.map_id, r.Item AS item_entry
  FROM (
    SELECT DISTINCT c.map AS map_id, ct.lootid
    FROM creature c JOIN creature_template ct ON ct.entry = c.id
    WHERE c.map IN (574,575,576,578,599,600,601,602,604,619,632,658) AND ct.lootid > 0
    UNION
    SELECT DISTINCT c.map AS map_id, heroic.lootid
    FROM creature c JOIN creature_template ct ON ct.entry = c.id
    JOIN creature_template heroic ON heroic.entry = ct.difficulty_entry_1
    WHERE c.map IN (574,575,576,578,599,600,601,602,604,619,632,658) AND heroic.lootid > 0
  ) loot_ids JOIN creature_loot_template l ON l.Entry = loot_ids.lootid
  JOIN reference_loot_template r ON r.Entry = l.Reference
  WHERE l.Reference > 0 AND r.Item > 0
) loot JOIN item_template src ON src.entry = loot.item_entry
WHERE src.Quality BETWEEN 3 AND 4 AND src.ItemLevel BETWEEN 175 AND 232
  AND src.RequiredLevel <= 80 AND src.InventoryType NOT IN (0,12)
  AND src.class IN (2,4) AND src.itemset = 0 AND src.startquest = 0;

DELETE FROM `item_template_locale` WHERE `ID` BETWEEN 9100000 AND 9899999;
DELETE FROM `item_template` WHERE `entry` BETWEEN 9100000 AND 9899999;

INSERT INTO `item_template` (
  `entry`,
  `class`,
  `subclass`,
  `SoundOverrideSubclass`,
  `name`,
  `displayid`,
  `Quality`,
  `Flags`,
  `FlagsExtra`,
  `BuyCount`,
  `BuyPrice`,
  `SellPrice`,
  `InventoryType`,
  `AllowableClass`,
  `AllowableRace`,
  `ItemLevel`,
  `RequiredLevel`,
  `RequiredSkill`,
  `RequiredSkillRank`,
  `requiredspell`,
  `requiredhonorrank`,
  `RequiredCityRank`,
  `RequiredReputationFaction`,
  `RequiredReputationRank`,
  `maxcount`,
  `stackable`,
  `ContainerSlots`,
  `stat_type1`,
  `stat_value1`,
  `stat_type2`,
  `stat_value2`,
  `stat_type3`,
  `stat_value3`,
  `stat_type4`,
  `stat_value4`,
  `stat_type5`,
  `stat_value5`,
  `stat_type6`,
  `stat_value6`,
  `stat_type7`,
  `stat_value7`,
  `stat_type8`,
  `stat_value8`,
  `stat_type9`,
  `stat_value9`,
  `stat_type10`,
  `stat_value10`,
  `ScalingStatDistribution`,
  `ScalingStatValue`,
  `dmg_min1`,
  `dmg_max1`,
  `dmg_type1`,
  `dmg_min2`,
  `dmg_max2`,
  `dmg_type2`,
  `armor`,
  `holy_res`,
  `fire_res`,
  `nature_res`,
  `frost_res`,
  `shadow_res`,
  `arcane_res`,
  `delay`,
  `ammo_type`,
  `RangedModRange`,
  `spellid_1`,
  `spelltrigger_1`,
  `spellcharges_1`,
  `spellppmRate_1`,
  `spellcooldown_1`,
  `spellcategory_1`,
  `spellcategorycooldown_1`,
  `spellid_2`,
  `spelltrigger_2`,
  `spellcharges_2`,
  `spellppmRate_2`,
  `spellcooldown_2`,
  `spellcategory_2`,
  `spellcategorycooldown_2`,
  `spellid_3`,
  `spelltrigger_3`,
  `spellcharges_3`,
  `spellppmRate_3`,
  `spellcooldown_3`,
  `spellcategory_3`,
  `spellcategorycooldown_3`,
  `spellid_4`,
  `spelltrigger_4`,
  `spellcharges_4`,
  `spellppmRate_4`,
  `spellcooldown_4`,
  `spellcategory_4`,
  `spellcategorycooldown_4`,
  `spellid_5`,
  `spelltrigger_5`,
  `spellcharges_5`,
  `spellppmRate_5`,
  `spellcooldown_5`,
  `spellcategory_5`,
  `spellcategorycooldown_5`,
  `bonding`,
  `description`,
  `PageText`,
  `LanguageID`,
  `PageMaterial`,
  `startquest`,
  `lockid`,
  `Material`,
  `sheath`,
  `RandomProperty`,
  `RandomSuffix`,
  `block`,
  `itemset`,
  `MaxDurability`,
  `area`,
  `Map`,
  `BagFamily`,
  `TotemCategory`,
  `socketColor_1`,
  `socketContent_1`,
  `socketColor_2`,
  `socketContent_2`,
  `socketColor_3`,
  `socketContent_3`,
  `socketBonus`,
  `GemProperties`,
  `RequiredDisenchantSkill`,
  `ArmorDamageModifier`,
  `duration`,
  `ItemLimitCategory`,
  `HolidayId`,
  `ScriptName`,
  `DisenchantID`,
  `FoodType`,
  `minMoneyLoot`,
  `maxMoneyLoot`,
  `flagsCustom`,
  `VerifiedBuild`
)
SELECT
  9000000 + (v.variant_id * 100000) + src.entry,
  src.`class`,
  src.`subclass`,
  src.`SoundOverrideSubclass`,
  CONCAT(src.name, ' [Mythic ', v.item_level, ']'),
  src.`displayid`,
  4,
  src.`Flags`,
  src.`FlagsExtra`,
  src.`BuyCount`,
  ROUND(src.`BuyPrice` * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED))),
  ROUND(src.`SellPrice` * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED))),
  src.`InventoryType`,
  src.`AllowableClass`,
  src.`AllowableRace`,
  v.item_level,
  80,
  src.`RequiredSkill`,
  src.`RequiredSkillRank`,
  src.`requiredspell`,
  src.`requiredhonorrank`,
  src.`RequiredCityRank`,
  0,
  0,
  0,
  src.`stackable`,
  src.`ContainerSlots`,
  src.`stat_type1`,
  ROUND(src.`stat_value1` * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  src.`stat_type2`,
  ROUND(src.`stat_value2` * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  src.`stat_type3`,
  ROUND(src.`stat_value3` * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  src.`stat_type4`,
  ROUND(src.`stat_value4` * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  src.`stat_type5`,
  ROUND(src.`stat_value5` * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  src.`stat_type6`,
  ROUND(src.`stat_value6` * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  src.`stat_type7`,
  ROUND(src.`stat_value7` * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  src.`stat_type8`,
  ROUND(src.`stat_value8` * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  src.`stat_type9`,
  ROUND(src.`stat_value9` * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  src.`stat_type10`,
  ROUND(src.`stat_value10` * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  0,
  0,
  ROUND(src.`dmg_min1` * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1), 2),
  ROUND(src.`dmg_max1` * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1), 2),
  src.`dmg_type1`,
  ROUND(src.`dmg_min2` * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1), 2),
  ROUND(src.`dmg_max2` * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1), 2),
  src.`dmg_type2`,
  ROUND(COALESCE(src.`armor`, 0) * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  ROUND(COALESCE(src.`holy_res`, 0) * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  ROUND(COALESCE(src.`fire_res`, 0) * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  ROUND(COALESCE(src.`nature_res`, 0) * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  ROUND(COALESCE(src.`frost_res`, 0) * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  ROUND(COALESCE(src.`shadow_res`, 0) * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  ROUND(COALESCE(src.`arcane_res`, 0) * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  src.`delay`,
  src.`ammo_type`,
  src.`RangedModRange`,
  0,
  0,
  0,
  0,
  -1,
  0,
  -1,
  0,
  0,
  0,
  0,
  -1,
  0,
  -1,
  0,
  0,
  0,
  0,
  -1,
  0,
  -1,
  0,
  0,
  0,
  0,
  -1,
  0,
  -1,
  0,
  0,
  0,
  0,
  -1,
  0,
  -1,
  1,
  src.`description`,
  src.`PageText`,
  src.`LanguageID`,
  src.`PageMaterial`,
  0,
  src.`lockid`,
  src.`Material`,
  src.`sheath`,
  0,
  0,
  ROUND(COALESCE(src.`block`, 0) * POWER(1.01, CAST(v.item_level AS SIGNED) - CAST(src.ItemLevel AS SIGNED)) * IF(src.Quality = 3, 1.12, 1)),
  0,
  src.`MaxDurability`,
  0,
  0,
  src.`BagFamily`,
  src.`TotemCategory`,
  src.`socketColor_1`,
  src.`socketContent_1`,
  src.`socketColor_2`,
  src.`socketContent_2`,
  src.`socketColor_3`,
  src.`socketContent_3`,
  src.`socketBonus`,
  src.`GemProperties`,
  -1,
  src.`ArmorDamageModifier`,
  0,
  0,
  0,
  '',
  0,
  src.`FoodType`,
  src.`minMoneyLoot`,
  src.`maxMoneyLoot`,
  src.`flagsCustom`,
  NULL
FROM `item_template` src
JOIN (SELECT DISTINCT `source_entry` FROM `mod_mythic_rewards_source`) source
  ON source.source_entry = src.entry
CROSS JOIN `mod_mythic_rewards_variant` v;

INSERT INTO `item_template_locale` (`ID`, `locale`, `Name`, `Description`, `VerifiedBuild`)
SELECT 9000000 + (v.variant_id * 100000) + locale.ID, locale.locale,
  CONCAT(locale.Name, IF(locale.locale IN ('zhCN','zhTW'), ' [大秘境 ', ' [Mythic '), v.item_level, ']'),
  locale.Description, NULL
FROM `item_template_locale` locale
JOIN (SELECT DISTINCT `source_entry` FROM `mod_mythic_rewards_source`) source
  ON source.source_entry = locale.ID
CROSS JOIN `mod_mythic_rewards_variant` v;

CREATE TABLE IF NOT EXISTS `mod_mythic_rewards_item_pool` (
  `map_id` smallint unsigned NOT NULL,
  `variant_id` tinyint unsigned NOT NULL,
  `source_entry` int unsigned NOT NULL,
  `item_entry` int unsigned NOT NULL,
  PRIMARY KEY (`map_id`, `variant_id`, `source_entry`),
  KEY `idx_pool` (`map_id`, `variant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DELETE FROM `mod_mythic_rewards_item_pool`;
INSERT INTO `mod_mythic_rewards_item_pool` (`map_id`, `variant_id`, `source_entry`, `item_entry`)
SELECT source.map_id, v.variant_id, source.source_entry,
  9000000 + (v.variant_id * 100000) + source.source_entry
FROM `mod_mythic_rewards_source` source CROSS JOIN `mod_mythic_rewards_variant` v;

DELETE FROM `acore_string` WHERE `entry` BETWEEN 85000 AND 85005;
INSERT INTO `acore_string`
(`entry`, `content_default`, `locale_koKR`, `locale_frFR`, `locale_deDE`, `locale_zhCN`, `locale_zhTW`, `locale_esES`, `locale_esMX`, `locale_ruRU`) VALUES
(85000, 'Mythic +{} reward: {}', '', '', '', '大秘境 +{} 奖励：{}', '', '', '', ''),
(85001, 'Mythic +{} reward mailed because your bags were full: {}', '', '', '', '背包已满，大秘境 +{} 奖励已邮寄：{}', '', '', '', ''),
(85002, 'Mythic +{} completed. No personal item this run; weekly reward progress was updated.', '', '', '', '大秘境 +{} 已完成。本次没有个人装备；每周奖励进度已更新。', '', '', '', ''),
(85003, 'Mythic +{} completed in time. Three personal items were awarded to the party.', '', '', '', '大秘境 +{} 限时完成，队伍共获得 3 件个人装备。', '', '', '', ''),
(85004, 'Mythic +{} completed over time. Two personal items were awarded to the party.', '', '', '', '大秘境 +{} 超时完成，队伍共获得 2 件个人装备。', '', '', '', ''),
(85005, 'Weekly Mythic reward for +{}: {}', '', '', '', '每周大秘境 +{} 奖励：{}', '', '', '', '');
